server:
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: classpath:serverkeystore.p12
    key-alias: 1
    key-store-password: "random"
    key-password: "random"
    trust-store: classpath:servertruststore.jks
    trust-store-password: "random"
    trust-store-type: JKS
    client-auth: need
  port: 9000
